- name: Installation d'Apache sur Web
  hosts: web
  become: yes
  vars_files:
    - "{{ ansible_os_family }}.yml"

  tasks:
    - name: Include OS-Specific
      include_vars: "{{ ansible_os_family }}.yml"

    - name: Suppression Apache
      package:
        name: "{{ apache_pkg }}"
        state: absent
